# Generated by Django 3.2.6 on 2022-03-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_like', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_like',
            name='user_like',
            field=models.IntegerField(default=0),
        ),
    ]
