# Generated by Django 3.2.6 on 2022-03-14 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_recommended', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_recommended',
            old_name='recommended',
            new_name='user_recommended',
        ),
    ]
