# Generated by Django 3.2.6 on 2022-03-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('reward', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=0)),
                ('coin', models.IntegerField(default=0)),
                ('active', models.SmallIntegerField(default=0)),
                ('phone_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
