# Generated by Django 3.2.6 on 2022-03-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_id',
            field=models.IntegerField(default=0),
        ),
    ]
