# Generated by Django 3.2.6 on 2022-04-01 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_app_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
